# File: azure-pipelines\nightly-snapshot-releases\Nightly Common VSTS Release.yml
# Description: Assemble & publish Snapshot common release nightly to internal feed
# https://identitydivision.visualstudio.com/Engineering/_packaging?_a=feed&feed=AndroidADAL
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none
pr: none

resources:
# TODO uncomment once we have a valid artifact in the pipeline
#  pipelines:
#  - pipeline: Android\Nightly Snapshot Releases\Nightly ADAL VSTS Release
#    project: Engineering
#    source: Nightly ADAL VSTS Release
#    trigger:
#      branches:
#        include:
#        - dev
  repositories:
  - repository: self
    type: git
    ref: dev

schedules:
- cron: 0 21 * * *
  branches:
    include:
    - dev
  always: true

jobs:
- template: ../templates/steps/nightly-snapshot-releases/common.yml
  parameters:
    versionType: Snapshot
