# File: azure-pipelines\templates\steps\nightly-snapshot-releases\common.yml
# Description: Template to assemble and publish Snapshot/Latest versions of common
# Variable: 'ENV_VSTS_MVN_ANDROIDCOMMON_USERNAME' was defined in the Variables tab
# Variable: 'mvnAccessToken' was defined in the Variables tab
# https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate
# Variable: 'versionType' type of version (Latest, Snapshot)

parameters:
- name: versionType
  default: Latest
  values:
  - Snapshot
  - Latest

jobs:
- job: Phase_1
  displayName: Phase 1
  timeoutInMinutes: 90
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - template: ../credscan-policheck.yml
    parameters:
      policheckCmdLineArgsDir: common
  - task: CmdLine@1
    displayName: Set MVN Access Token in Environment
    inputs:
      filename: echo
      arguments: '##vso[task.setvariable variable=ENV_VSTS_MVN_ANDROIDCOMMON_ACCESSTOKEN]$(mvnAccessToken)'
  - task: Gradle@2
    displayName: ${{ parameters.versionType }} version update
    inputs:
      tasks: common:version${{ parameters.versionType }}
      publishJUnitResults: false
  - task: Gradle@1
    name: Gradle1
    displayName: Assemble Release
    inputs:
      tasks: 'clean common:build common:assembleRelease'
      publishJUnitResults: false
      jdkArchitecture: x86
      sqAnalysisBreakBuildIfQualityGateFailed: false
  - task: Gradle@2
    displayName: Run unit tests
    inputs:
      tasks: testDebugUnitTest
  - task: Gradle@2
    displayName: Publish
    inputs:
      tasks: common:publish
      publishJUnitResults: false
  - task: CopyFiles@2
    name: CopyFiles1
    displayName: Copy Files to Artifact Staging Directory
    inputs:
      SourceFolder: common\build\
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishPipelineArtifact@1
    name: PublishPipelineArtifacts1
    displayName: 'Publish Artifact: Common Release'
    inputs:
      ArtifactName: CommonRelease
      TargetPath: $(Build.SourcesDirectory)/common/build/
  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Detection
...
