# File: azure-pipelines\auth-client\instrumented-test.yml
# Description: Run instrumented test in docker conatiner
name: Instrumented Tests

trigger:
- main

pool:
 name: DockerBuildAgents

jobs:
- job: instrumentedTest
  displayName: Instrumented Test
  workspace:
    clean: all
  steps:
  - template: ../templates/steps/auth-client/docker-tasks.yml
