# File: azure-pipelines\pull-request-validation\common.yml
# Description: Assemble and run unit test
name: $(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - dev
    - master
  batch: True

resources:
  repositories:
  - repository: self
    type: git
    ref: dev

jobs:
- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - checkout: self
    clean: true
    submodules: recursive
    persistCredentials: True
  - template: ../templates/steps/credscan-policheck.yml
    parameters:
      policheckCmdLineArgsDir: common
  - template: ../templates/steps/automation-cert.yml
  - task: Gradle@1
    name: Gradle1
    displayName: Assemble Release
    inputs:
      tasks: clean common:assemble
      publishJUnitResults: false
      jdkArchitecture: x86
      sqAnalysisBreakBuildIfQualityGateFailed: false
  - task: Gradle@2
    displayName: Run Unit tests
    inputs:
      tasks: common:testDebugUnitTest
  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Detection
...
